### ISSUE TITLE
Suggestion: Ladies Wine and Design

### ISSUE THREAD

**Issue by mhamilt** [cristianoliveira/awesome4girls#162]
Not strictly bound to coding, but [Ladies Wine and Design](https://ladieswinedesign.com) seem to do a lot of cross over events that are development based.

**Comment by harsh183** [comment]
It is not all coding but I think we should add it.

Since it doesn't too neatly cross over to our categories so I think we can just add another category within Events called `Design` and put this there.

@mhamilt Would you want to add this? Just edit the `README.md` file in the right section and follow the format that other entries have.

**Comment by mhamilt** [comment]
Of course, will get it done shortly

**Comment by harsh183** [comment]
Great. Submit a PR once done and I'll take care of it.

**Comment by cristianoliveira** [comment]
The #164 It's been merged containing this :)
