### ISSUE TITLE
Add resources from this Women in Tech page 

### ISSUE THREAD

**Issue by harsh183** [cristianoliveira/awesome4girls#177]
https://github.com/nishapant/Women-in-Tech-Resources

Or maybe just link to it. It hasn't been updated in a few years though.

**Comment by rkraeher** [comment]
Is this issue still available or is this something you were proposing to do yourself @harsh183?

since you mention that repo hasn't been updated for a while, I could comb through their list and find the resources that are current and non-duplicates (I've already found a few) and then put them into the appropriate place in the list here.

**Comment by harsh183** [comment]
I would appreciate that so much! @rkraeher 

Tag me when you make a Pull Request with this. Don't worry if it's failing due to some old links here but I'll sort that stuff out myself.

**Comment by rkraeher** [comment]
I have a question:

The contributing doc says that each suggestion should be a separate PR. There are 12 new resources to add to the list here that I've found from the Women-in-Tech-Resources list. Should I do all 12 as separate PRs, separate commits but one PR, or just one commit and PR since we have a record here of where they came from? 

Sorry if this is obvious from the docs. I'm new to contributing.

**Comment by harsh183** [comment]
Up to you. I think the repo is a little stale so let's start with a single PR we merge in, and then the rest we can do in one go. 

I think since it's been a while some old links might have broken so we definitely have to sort those out as well. Would you be down to help with that?

**Comment by rkraeher** [comment]
Ok sounds good thanks. Yes, deffly down to help with that. I've already found two that I wrote down. I can open a broken link issue (?) and I'll work on those once I do the PR for these new additions.

**Comment by harsh183** [comment]
Sweet. If you check we have some automated tests that checks for a lot of baseline issues (formatting, working link etc.) so you'll just have to fix what it says. You'll be able to access the list once you made a PR and the CI runs those tests.
